# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  mytasks.in:
    site_hosts:
      - canonical: mytasks.dev
        redirects:
          - www.mytasks.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: dilip@mytasks.dev
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    env:
      wp_home: http://mytasks.dev
      wp_siteurl: http://mytasks.dev/wp