# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: productionpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: password
    salt: "sa"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  mytasks.in:
    env:
      db_password: dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "v@M|U&E)x%+!H3YvBdAJ*NVOHW|fuJXP+P!<96:&w+fg?<m/w+=IuJDzpz*(7X){"
      secure_auth_key: "]#OgDd$f}]0gqWfi<tD_GjcBvB3I_=l^-B4qmZkd?B_DzZ9Ek&A=6Q4dU:yl6X4C"
      logged_in_key: "e]>1:]_E0yvL:81)Nh&s(k{oQgw.l$vU)K;MgJYO<:uzT[!S[02;nI<`}mbRhS{2"
      nonce_key: "7t4l1o3AUd+dX7nVZhwS06VJYj`>L1f3dgEFAGVe.tjcH`>/R`#E}DCAFM#StnG0"
      auth_salt: "Olq)=uYHB,:ng6JgA#L2nXlXr}8n-LJm]}il[$K/t3q{2D.<[3J)$fw@PKfTupll"
      secure_auth_salt: "E-R-k%ZKSZad67bt{x;{]+T.0+/=d0=diC%kGjd1DPn4$0LSlSa=0x_68;dk=khX"
      logged_in_salt: "(UtA9,KVaEitua9iq,<``rJkNK/R+0+nYM*RBCW]1QKGK_@!PA[@ML*sLKnGiPu{"
      nonce_salt: "<YZTq0oJ1o}h+Je@-mtdfKmg-%T3rP;?r+##0>y_bGIG*PZFM{rn+NUv!Nv/IbHn"